engines:
  fixme:
    enabled: true
    config:
      strings:
      - legacy
      - WIP
  eslint:
    enabled: true
ratings:
  paths:
    - "**.js"
exclude_paths:
- "**/*.md"
- ".codeclimate.yml"
- "Dockerfile"
- "bin/fixme"
- "test/**"
